server:
  port: 10000

spring:
  cloud:
    nacos:
      discovery:
        namespace: dev
        server-addr: 139.196.153.80:8849
        register-enabled: true
        username: nacos
        password: nacos
#      routes:   # 网关服务路由配置
#        - id: user-service   # 服务id
#          order: 1      #优先级
#          predicates:   #规则定义
#            - Path=/api/v1/users/**
#          uri: lb://user-service   #服务url
#          filters:
#            - StripPrefix=2
#        - id: content-service
#          order: 1
#          predicates:
#            - Path=/api/v1/shares/**
#          uri: lb://content-service
#          filters:
#            - StripPrefix=2021
#        - id: notice-service
#          order: 1
#          predicates:
#            - Path=/api/v1/notices/**
#          uri: lb://notice-service
#          filters:
#            - StripPrefix=2

